// <auto-generated />
using Aula10_Avaliacao_G1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Aula10AvaliacaoG1.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20181008145442_PlanosClientesConsultas")]
    partial class PlanosClientesConsultas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("Aula10_Avaliacao_G1.Models.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("dataNascimento");

                    b.Property<string>("email");

                    b.Property<string>("endereco");

                    b.Property<string>("fone");

                    b.Property<string>("nome");

                    b.Property<int?>("planoid");

                    b.HasKey("id");

                    b.HasIndex("planoid");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Aula10_Avaliacao_G1.Models.Consulta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("clienteid");

                    b.Property<string>("data");

                    b.Property<string>("descricao");

                    b.Property<string>("horario");

                    b.Property<string>("numeroDeConsultas");

                    b.Property<string>("status");

                    b.Property<double>("valor");

                    b.HasKey("id");

                    b.HasIndex("clienteid");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("Aula10_Avaliacao_G1.Models.Plano", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("nome");

                    b.HasKey("id");

                    b.ToTable("Planos");
                });

            modelBuilder.Entity("Aula10_Avaliacao_G1.Models.Cliente", b =>
                {
                    b.HasOne("Aula10_Avaliacao_G1.Models.Plano", "plano")
                        .WithMany()
                        .HasForeignKey("planoid");
                });

            modelBuilder.Entity("Aula10_Avaliacao_G1.Models.Consulta", b =>
                {
                    b.HasOne("Aula10_Avaliacao_G1.Models.Cliente", "cliente")
                        .WithMany()
                        .HasForeignKey("clienteid");
                });
#pragma warning restore 612, 618
        }
    }
}
